AWSTemplateFormatVersion: "2010-09-09"

Description: Basic VPC Infrastructure with one public subnet, an Internet Gateway, and route table rules.

Parameters:
  VPCName:
    Description: Name of the VPC
    Type: String
    Default: MigrationVPC
  VPCCidr:
    Description: CIDR range for the VPC
    Type: String
    Default: "192.168.0.0/16"
  PublicSubnetCidr:
    Description: CIDR range for the public subnet
    Type: String
    Default: "192.168.10.0/24"

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref VPCName

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PublicSubnetCidr
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${VPCName}-Public-Subnet"

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${VPCName}-Internet-Gateway"

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: !Sub "${VPCName}-Public-Route-Table"

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

Outputs:
  VPCId:
    Description: ID of the VPC
    Value: !Ref MyVPC

  PublicSubnetId:
    Description: ID of the public subnet
    Value: !Ref PublicSubnet

  InternetGatewayId:
    Description: ID of the Internet Gateway
    Value: !Ref InternetGateway
